/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nickming_testapp_jni_TestJniUtils */

#ifndef _Included_com_nickming_testapp_jni_TestJniUtils
#define _Included_com_nickming_testapp_jni_TestJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nickming_testapp_jni_TestJniUtils
 * Method:    getStrFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nickming_testapp_jni_TestJniUtils_getStrFromJni
  (JNIEnv *, jclass);

/*
 * Class:     com_nickming_testapp_jni_TestJniUtils
 * Method:    deliverStrToJni
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_nickming_testapp_jni_TestJniUtils_deliverStrToJni
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
